### ISSUE TITLE
Executor for dart_native needs environment setup to execute

### ISSUE THREAD

**Issue by sven-oly** [unicode-org/conformance#86]
Testdriver with dart_native gives this in Linux environment. This needs to be fixed to run dart_native tests.

    ----> STDOUT= ><
 !!!!!! !!!! ERROR IN EXECUTION: 255. STDERR = Unhandled exception:
UnimplementedError: Insert diplomat bindings here
#0      Collation4X.compareImpl (package:intl4x/src/collation/collation_4x.dart:16)
#1      Collation.compare (package:intl4x/src/collation/collation.dart:28)
#2      testCollator (file:///usr/local/google/home/ccornelius/ICU_conformance/conformance/executors/dart_native/bin/executor.dart:74)
#3      main.<anonymous closure> (file:///usr/local/google/home/ccornelius/ICU_conformance/conformance/executors/dart_native/bin/executor.dart:49)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776)
#8      _StreamController._add (dart:async/stream_controller.dart:650)
#9      _StreamController.add (dart:async/stream_controller.dart:598)
#10     _Socket._onData (dart:io-patch/socket_patch.dart:2381)
#11     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#14     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776)
#15     _StreamController._add (dart:async/stream_controller.dart:650)
#16     _StreamController.add (dart:async/stream_controller.dart:598)
#17     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1899)
#18     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1356)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123)
#22     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:190)
WARNING:root:!!!!!! process_batch_of_tests: "platform error": "!!!! ERROR IN EXECUTION: 255. STDERR = Unhandled exception:
UnimplementedError: Insert diplomat bindings here
#0      Collation4X.compareImpl (package:intl4x/src/collation/collation_4x.dart:16)
#1      Collation.compare (package:intl4x/src/collation/collation.dart:28)
#2      testCollator (file:///usr/local/google/home/ccornelius/ICU_conformance/conformance/executors/dart_native/bin/executor.dart:74)
#3      main.<anonymous closure> (file:///usr/local/google/home/ccornelius/ICU_conformance/conformance/executors/dart_native/bin/executor.dart:49)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776)
#8      _StreamController._add (dart:async/stream_controller.dart:650)
#9      _StreamController.add (dart:async/stream_controller.dart:598)
#10     _Socket._onData (dart:io-patch/socket_patch.dart:2381)
#11     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#14     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776)
#15     _StreamController._add (dart:async/stream_controller.dart:650)
#16     _StreamController.add (dart:async/stream_controller.dart:598)
#17     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1899)
#18     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1356)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123)
#22     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:190)
"

**Comment by sffc** [comment]
@mosuem Are we still running Dart Native testing? We should try to make sure this is running in CI and appearing on the dashboard.
